stages:
  - test
  - publish

services:
  - docker:dind

before_script:
  - docker info
  - docker login -p $ARTIFACTORY_PASSWORD -u $ARTIFACTORY_USERNAME edify-dkr.jfrog.io

test-debug:
  image: node:6.9.1
  stage: test
  script:
    - curl -u$ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD https://edify.jfrog.io/edify/api/npm/auth > ~/.npmrc
    - echo registry=http://edify.jfrog.io/edify/api/npm/npm-edify >> ~/.npmrc
    - npm install

release-docker:
  image: node:6.9.1
  stage: publish
  only:
    - master
  script:
    - curl -u$ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD https://edify.jfrog.io/edify/api/npm/auth > ~/.npmrc
    - echo registry=http://edify.jfrog.io/edify/api/npm/npm-edify >> ~/.npmrc
    - npm install
    - docker build -t cl-index .
